### ISSUE TITLE
Public ConfigurationContext.TypeScanners

### ISSUE THREAD

**Issue by Martijn-Sharp** [valdisiljuconoks/LocalizationProvider#101]
Hey Valdis!

I'd like to add my own scanner in a project I'm working on, but the TypeScanners property is made internal and not useable for me.
Would you consider making it public so we can add our own scanners?

Cheers

**Comment by valdisiljuconoks** [comment]
Hi,

You. This might be a good idea.

**Comment by valdisiljuconoks** [comment]
Consolidating couple of features before pushing to nuget..

**Comment by valdisiljuconoks** [comment]
v2.8.3
