### ISSUE TITLE
LocalizedResourceAttribute KeyPrefix doesn't work with nested resources

### ISSUE THREAD

**Issue by Martijn-Sharp** [valdisiljuconoks/LocalizationProvider#102]
Hello tharrr,

I'm running into an issue that might be a bug.
Using nested resource classes with the `KeyPrefix` property on the LocalizedResource attribute, that decorates the lowest class, doesn't seem to work when using `LocalizationProvider.GetStringByCulture(...)` or `@Html.Translate(...)` in Razor.

Working example:

``` csharp
[LocalizedResource]
public class ContentpagesResources
{
    public static HeaderResources Header { get; }

    public static TabsResources Tabs { get; }

    public class HeaderResources
    {
        public string BlogPage => "Blog";
    }

    public class TabsResources
    {
        public string Overview => "Overview";
    }
}

LocalizationProvider.GetStringByCulture(() => ContentpagesResources.Tabs.Overview, page.Language)
```

Non-working example:

``` csharp
[LocalizedResource(KeyPrefix = "Contentpages")]
public class ContentpagesResources
{
    public static HeaderResources Header { get; }

    public static TabsResources Tabs { get; }

    public class HeaderResources
    {
        public string BlogPage => "Blog";
    }

    public class TabsResources
    {
        public string Overview => "Overview";
    }
}

LocalizationProvider.GetStringByCulture(() => ContentpagesResources.Tabs.Overview, page.Language)
```

I'm using the approach as described in https://blog.tech-fellow.net/2016/03/16/db-localization-provider-part-1-resources-and-models/

This is not a critical bug, I'll just continue with enormous keys (the full namespace part), but if you happen to know an other way to achieve shorter keys, then i'll be happy to hear it!

Adios

**Comment by valdisiljuconoks** [comment]
Hey,

This definitely looks like a bug. I'll need to investigate more a bit here. Seems like resource keys are not propagated down..

**Comment by valdisiljuconoks** [comment]
will pack together with other smaller updates and push to nuget.

**Comment by valdisiljuconoks** [comment]
v2.8.3
