### ISSUE TITLE
DbLocalizationProvider.EPiServer.JsResourceHandler

### ISSUE THREAD

**Issue by hemant-bam** [valdisiljuconoks/LocalizationProvider#104]
Rendering @Html.GetTranslations(typeof(MyResource)) generates 404 error.

**Comment by valdisiljuconoks** [comment]
what is the link in markup? can you paste `<system.webServer><handlers>` section?

**Comment by hemant-bam** [comment]
Script tag is generated as <script src="jsl10n/MyResource"/>
Handler as
<add name="JsResourceHandler" path="/jsl10n/*" verb="GET" type="DbLocalizationProvider.EPiServer.JsResourceHandler.HttpHandler, DbLocalizationProvider.EPiServer.JsResourceHandler" />

**Comment by valdisiljuconoks** [comment]
script tag should be rendered with `/jsl10n/..` path and not with `jsl10n/..`. I checked the code and see no reason why leading slash `/` could be omitted. Do you have some outgoing link rewrite rules applied to the project? Can you replicate this in empty AlloyTech site?

**Comment by hemant-bam** [comment]
Sorry my bad, I missed the leading slash while commenting on this thread. We do have some virtual path re write rules (internal links only) to support SEO.  I assume, HttpHandler would intercept the route and serve the request. I have not tested this feature with empty alloy site though.

**Comment by valdisiljuconoks** [comment]
please, try to replicate this issue in alloytech. I can verify that this is working on my versions..

**Comment by valdisiljuconoks** [comment]
hi, isn't so that you tried to get resources from nested resource class?

**Comment by valdisiljuconoks** [comment]
hi,

what's update here? An we close this issue? Did you solve?
