### ISSUE TITLE
Episerver Provider

### ISSUE THREAD

**Issue by bmcdavid** [valdisiljuconoks/LocalizationProvider#110]
Hi Valdis,

Would you be able to drop the EPiServer.ServiceLocation.StructureMap package dependency in DbLocalizationProvider.EPiServer and use a similar approach to what I did here: https://gist.github.com/bmcdavid/2f335314b3bda9839f34acbc31c1a903 (ie using ServiceLocator during init complete). 

The reasoning is I believe, Epi will soon allow for Structuremap 4.x, using this assembly attribute: EPiServer.ServiceLocation.AutoDiscovery.ServiceLocatorFactory.

I've worked out an example below in a test Alloy site:
```cs
// this will allow a different Structuremap version
[assembly: EPiServer.ServiceLocation.AutoDiscovery.ServiceLocatorFactory(typeof(AlloyCms11.ACustomContainer))]

namespace AlloyCms11
{
    /// <summary>
    /// Custom IServiceLocator, i'm guessing alpa sorted by assembly name sorted currently wins
    /// </summary>
    public class ACustomContainer : EPiServer.ServiceLocation.AutoDiscovery.IServiceLocatorFactory
    {
        StructureMap.IContainer _container = new StructureMap.Container();

        public EPiServer.ServiceLocation.IServiceLocator CreateLocator()
        {
            return new EPiServer.ServiceLocation.StructureMapServiceLocator(_container);
        }

        public EPiServer.ServiceLocation.IServiceConfigurationProvider CreateProvider()
        {
            return new EPiServer.ServiceLocation.Internal.StructureMapConfiguration(_container);
        }
    }
}
```
Let me know if you have any questions about this.

Thanks,
Brad

**Comment by valdisiljuconoks** [comment]
yeah, remember you asked.. so reason to get rid of SM dependency is to be able to use another IoC in the future?

**Comment by valdisiljuconoks** [comment]
seems like working. thx

**Comment by bmcdavid** [comment]
Awesome, thanks for quick turn around!

**Comment by valdisiljuconoks** [comment]
thx for tip
