### ISSUE TITLE
Migration tools exported values doesn't get imported

### ISSUE THREAD

**Issue by jerry84** [valdisiljuconoks/LocalizationProvider#115]
I am using the  migration tool to generate the `json` file. After that I tried to use the AdminUI to import the file. However only the translation keys got imported but not the translations values. Here is an example of the generated `json`
``` json
[
  {
    "resourceKey": "/Shared/Close",
    "modificationDate": "2017-12-18T06:42:33.5225633Z",
    "author": "migration-tool",
    "translations": [
      {
        "language": "fi-FI",
        "value": "Sulje"
      },
      {
        "language": "no",
        "value": "Lukk"
      },
      {
        "language": "sv-SE",
        "value": "Stäng"
      }
    ]
  },
```
Do you have any suggestion to solve this?

**Comment by valdisiljuconoks** [comment]
What happens if you go via preview of the import process in AdminUI? Are all mentioned languages enabled in target Episerver site?

**Comment by jerry84** [comment]
Yes, all the languages are enabled as far as I can see in the AdminUI
## Screen dump
![image](https://user-images.githubusercontent.com/228484/34100963-77fd920a-e3e4-11e7-8c74-bb2713deee4b.png)

**Comment by valdisiljuconoks** [comment]
Check language codes in Admin/Manage Website Languages.

Json file contains language and region code (fi-FI). Usually by default in Episerver - there is only language code and not together with region.

**Comment by jerry84** [comment]
We do use `fi-FI` in website languages

Am I suppose to see the values in the preview mode before import?

**Comment by valdisiljuconoks** [comment]
Ok then. Yes - in preview you should see what import process decided to import. Give it a try.

**Comment by valdisiljuconoks** [comment]
which versions of libraries you are using now? will cross check now..

**Comment by jerry84** [comment]
I am using v3.6.0 on `AdminUI.Episerver`, `Episerver` and `MigrationTool`

**Comment by valdisiljuconoks** [comment]
yes, indeed. seems like changed resource language detection was broken. rolling out fix

**Comment by jerry84** [comment]
Cool! Thanks for fixing it 👍

**Comment by valdisiljuconoks** [comment]
you should wait for 3.6.1 version when available on Episerver feed.
