### ISSUE TITLE
DbLocalizationProvider.AdminUI.EPiServer Dependencies

### ISSUE THREAD

**Issue by vnbaaij** [valdisiljuconoks/LocalizationProvider#117]
DbLocalizationProvider.AdminUI.EPiServer has dependencies on structuremap.web-signed (3.1.6.191) and structuremap-signed (3.1.9.463). Episerver 11 now uses (the unsigned) version 4 of StructureMap. We now need to have both StructureMap packages in our solution (AlloyDemoKit) and this leads to a compiler warning (No way to resolve conflict between "StructureMap, Version=4.0.0.315, Culture=neutral, PublicKeyToken=null" and "StructureMap, Version=3.1.9.463, Culture=neutral, PublicKeyToken=e60ad81abae3c223". Choosing "StructureMap, Version=4.0.0.315, Culture=neutral, PublicKeyToken=null" arbitrarily.)

Is it possible to upgrade your code so it also uses the StructureMap v4 package?

**Comment by valdisiljuconoks** [comment]
of course, where are my manners?! IMHO AdminUI package does not require SM at all..

**Comment by vnbaaij** [comment]
Wow that was fast. Thanks!
