### ISSUE TITLE
Issue when combining DisplayAttribute, ResourceKeyAttribute and RequiredAttribute

### ISSUE THREAD

**Issue by btsvennes** [valdisiljuconoks/LocalizationProvider#119]
Hi.

First of all, thank you very much for an excellent addition to Episerver.

I have an issue when using the ResourceKeyAttribute along with the DisplayAttribute and a validation attribute, for instance the RequiredAttribute, in my view model (ASP.net MVC). The ResourceKeyAttribute correctly changes the standard resource key to what I specify. But no attribute is created for the RequiredAttribute. If I set my ResourceKey to for instance "Language.Labels.Mail" I'm expecting a "Language.Labels.Mail-Required" resource to be present, but there is none.

Regards,
Bjørn Terje Svennes

**Comment by valdisiljuconoks** [comment]
Hi and thanks!

No surprises, IMHO this combination is not actually entirely supported. One question before proceeding - any reasons you need to specify resource key for view model properties?

**Comment by btsvennes** [comment]
The reason why is that we want to migrate our existing resource files. And because we want to use your new Expression-way of retrieving these, we created a custom migration tool that just generate CS-files with the correct setup. The resources also contains strings for the Display-, Required-, RegularExpressionAttribute and so on. So we have to specify the resource key to make our view models use the correct string. We are aware that using ResourceKeyAttribute only controls were DisplayAttribute retrieves its value, but this is better than nothing. In a perferct world it would be nice to specify the resource key for all attributes, but this means making custom versions of all attributes. This would be a working solution, but we try to employ out-of-the-box features.

**Comment by valdisiljuconoks** [comment]
.xml -> .cs generator sounds like an interesting addition ;)

so, do I understand it correctly that feature you are looking for would be:

out if this model:
```
public class MyModel
{
    [ResourceKey("my-key")]
    [Required]
    [StringLength(10)]
    public string UserName { get; set; }
}
```

I would get following resource keys:

```
my-key // for display
my-key-Required
my-key-StringLength
```

**Comment by btsvennes** [comment]
That's correct. Ideally we would want something like this:
`public class MyModel
{
    [Display(ResourceKey = "my-key")]
    [Required(ResourceKey = "my-required-validation-key")]
    [StringLength(10, ResourceKey = "my-length-validation-key")]
    public string UserName { get; set; }
}`
But, as stated earlier, we understand that this would require creating new versions for all attributes. So your suggestion is more along the lines of what is already present in your DbLocalizationProvider.

**Comment by btsvennes** [comment]
Hello again.

An addition to this: It seems like there is some chance when it comes to discovery of LocalizedResource and LocalizedModel. As mentioned earlier, we use the ResourceKeyAttribute to make use of resources migrated into classes decorated with the LocalizedResource-attribute. Let's say there is a resource with key (or rather property name) "Label.Email" defined as a property "Email" in a class "Label". In a view model, decorated with the LocalizedModel-attribute, I use this resource by adding the ResourceKey-attribute to the property in the view model wich is decorated with the Display-attribute with no parameteres:
'''
[LocalizedResource]
public class Label
{
     public static string Email => "E-mail";
}
'''
'''
[LocalizedModel(OnlyIncluded = true)]
public class ViewModel
{
     [Include]
     [Display]
     [ResourceKey("Label.Email")]
     public string Email { get; set; }
}
'''
Sometimes the Email gets the value "E-mail" and sometimes the value "Email" (name of the property). Will this be resolved by the enhancement?

**Comment by valdisiljuconoks** [comment]
Sometimes?! Hmm even more interesting.. are you using cached model metadata providers?

Ideally would be if you can share repro project, that would save time for me to rebuild your context..

**Comment by btsvennes** [comment]
My previous statement was not quite accurate. The texts doesn't change at run time, but between web application startups. We are not using any caching on metadata.

Unfortunately I cannot share the project, since it belongs to a customer of ours.

From what I've seen it looks like it depends on which classes are being discovered first and second; the view model og the resource.

**Comment by valdisiljuconoks** [comment]
ok, I see. anyhow - your proposed solution sounds a bit hackish ;) so we need to find proper solution..

**Comment by valdisiljuconoks** [comment]
update here - I'm working on this feature. For now - reviewing how to make this happen with backward compatibility in mind :) sometimes not trivial...

**Comment by valdisiljuconoks** [comment]
I do have a prototype of upcoming changes. Wanna try via preview packages? Btw, we are talking about CMS 11, right?

**Comment by btsvennes** [comment]
Great! Yes, I would like to try it. And yes, we are on CMS 11.

**Comment by valdisiljuconoks** [comment]
drop me mail here: valdis dot iljuconoks at outlook dot com
