### ISSUE TITLE
Not possible to use app.config in MigrationTool

### ISSUE THREAD

**Issue by jerry84** [valdisiljuconoks/LocalizationProvider#126]
The migration tool requires to have `Web.config` in the source folder.
https://github.com/valdisiljuconoks/LocalizationProvider/blob/1f6a52116f57296fa0d091b8a74b52dbd3eab1ad/src/DbLocalizationProvider.MigrationTool/Program.cs#L36

It would be nice to supporting `App.config` as well.

**Comment by valdisiljuconoks** [comment]
What is use case when you need to read Episerver settings from `app.config` file?

**Comment by jerry84** [comment]
I am using this in a sub project within the solution where `web.config` does not exist.
