### ISSUE TITLE
Version 3.6.0 - Import Resources

### ISSUE THREAD

**Issue by johnhydemtm365** [valdisiljuconoks/LocalizationProvider#127]
Hi there not sure if this issue has been fixed in a later version, could not see. Also we cannot upgrade to latest version as we do not want to upgrade to 11 just now.

However when we import the resources we have exported locally, it imports the keys but not the values for the relevant languages .......

Thanks
J

**Comment by jerry84** [comment]
It should be fixed in `3.6.1` for the AdminUI

**Comment by johnhydemtm365** [comment]
Thought I had tried that one, just done it again and it worked!
Thanks
J
