### ISSUE TITLE
Poor performing query 

### ISSUE THREAD

**Issue by markeverard** [valdisiljuconoks/LocalizationProvider#137]
Hey Waldis, 

We're using this on a high traffic site and we've had reports that the following query is consuming high CPU from the DXC team.

I can't really figure out the purpose of the query (beyond its EF generated) and where it might be executed and why it might perform poorly.

Any chance you can point me in the right direction.......

Thank you Obi-Wan.

SELECT 
[Project1].[Id] AS [Id], 
[Project1].[ResourceKey] AS [ResourceKey], 
[Project1].[ModificationDate] AS [ModificationDate], 
[Project1].[Author] AS [Author], 
[Project1].[FromCode] AS [FromCode], 
[Project1].[IsModified] AS [IsModified], 
[Project1].[IsHidden] AS [IsHidden], 
[Project1].[C1] AS [C1], 
[Project1].[Id1] AS [Id1], 
[Project1].[ResourceId] AS [ResourceId], 
[Project1].[Language] AS [Language], 
[Project1].[Value] AS [Value], 
[Project1].[LocalizationResource_Id] AS [LocalizationResource_Id]
FROM ( SELECT 
[Extent1].[Id] AS [Id], 
[Extent1].[ResourceKey] AS [ResourceKey], 
[Extent1].[ModificationDate] AS [ModificationDate], 
[Extent1].[Author] AS [Author], 
[Extent1].[FromCode] AS [FromCode], 
[Extent1].[IsModified] AS [IsModified], 
[Extent1].[IsHidden] AS [IsHidden], 
[Extent2].[Id] AS [Id1], 
[Extent2].[ResourceId] AS [ResourceId], 
[Extent2].[Language] AS [Language], 
[Extent2].[Value] AS [Value], 
[Extent2].[LocalizationResource_Id] AS [LocalizationResource_Id], 
CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
FROM [dbo].[LocalizationResources] AS [Extent1]
LEFT OUTER JOIN [dbo].[LocalizationResourceTranslations] AS [Extent2] ON [Extent1].[Id] = [Extent2].[ResourceId]
) AS [Project1]
ORDER BY [Project1].[Id] ASC, [Project1].[C1] ASC

**Comment by IInvocation** [comment]
Hi, not Waldis here - but as far as i know:
LocalizationProvider initially fetches every localization placing it in a cache, which is obviously slow. However: This shouldnt really matter much, since this only happens at startup. Does this happen more often for you?

**Comment by valdisiljuconoks** [comment]
morgen Mark,

need more data. how many resources & languages you have? is caching enabled? is caching enabled to be populated at startup? how long is long? how often does it happen?

AdminUI as far as I remember fetches all resources straight from db. if someone is constantly refreshing that page with zillions of resources - it might get noticed.

**Comment by valdisiljuconoks** [comment]
this is bugging me :) aand also version numbers you used in the site makes sense. there were couple of fixes around cache lately...

**Comment by valdisiljuconoks** [comment]
hi,

late to the party here. but.. I just discovered that every time when someone is accessing admin UI -> library calls directly database (skipping caching layer) to retrieve list of resources. this might be a perf. penalty here..

**Comment by valdisiljuconoks** [comment]
@mark - any follow here? can we close this?

**Comment by valdisiljuconoks** [comment]
hi, this should be now fixed in v5.2
