### ISSUE TITLE
Model with data annotation attributes cannot have more than one `[ResourceKey]` attribute.

### ISSUE THREAD

**Issue by bsubasic** [valdisiljuconoks/LocalizationProvider#138]
Hi,

I'm using the latest ver. 4.3.5 on an EpiServer ver. 11.1.0 for localizing UI editor property names and descriptions. 

When I tried to annotate this kind of property displayed below, I got an exception "Model with data annotation attributes cannot have more than one `[ResourceKey]` attribute.".

```       
        [Include]
        [ResourceKey("properties/contentsections/caption", Value = "Page sections")]
        [ResourceKey("properties/contentsections/help", Value = "Set ordered page sections based on different block types")]
        [Display(Name = "Page sections",
            Description = "Set ordered page sections based on different block types",
            GroupName = SystemTabNames.Content,
            Order = 3)]
        [AllowedTypes(typeof(ContentSectionBlock), typeof(DocumentsSectionBlock))]
        public virtual ContentArea ContentSections { get; set; } 
```

I don't know why this limit exists, but how I can tell LocalizationProvider to not include "AllowedTypes" Epi attribute as I don't need it, and to let me use these two ResourceKey attributes?

Can I turn off specific attributes in InitializableModule or how to handle this situation?

Thanks,
Bojan

**Comment by valdisiljuconoks** [comment]
do you have `[LocalizedModel]` or `[LocalizedResource]` on top of the class? Are you using this class as view model as well or just using it as container for the resources?
Don't think that there is feature now to ignore some attribute. Might be a good feature addition, thx.

The most easiest workaround for now would be to have separate class with just "mimic" of this class and just decorate with `[ResourceKey]` attributes to get correct resources into db. even more silly would be to have just 1 property with all necessary `[ResourceKey]` and appropriate xpath-es.

reason for this exception might require blog post on its own ;)

**Comment by bsubasic** [comment]
I have this annotation on a standard Epi page type class inheriting PageData, so it only picks up properties that I want to translate in editor mode.

 `[LocalizedModel(KeyPrefix = "/contenttypes/contactpage/", Inherited = false, OnlyIncluded = true)]`

I have this page model class referenced as "CurrentPage" in my ViewModels that are used in templates, so I use it directly for simple data properties. 

I don't want to mess with XML localization files, this plugin is way better for many reasons.

Yes, I understand your suggestion and I will probably go with that.

Because of this limitation, it would be nice to have some config option where we can add attributes to ignore. Then we can add everything in one place, where it should be ;)

Thanks

**Comment by valdisiljuconoks** [comment]
think you can safely go with `[LocalizedResource]` if you are not using it as view model (like `@Html.LabelFor(_ => Model.CurrentPage)`) and expecting proper label from `[ResourceKey]` attribute to be rendered. 

it class is just for resource keys - then you don't need model

**Comment by bsubasic** [comment]
Good, understood. I will give it a try.

**Comment by bsubasic** [comment]
Just to confirm it works.

I've extracted an interface from the page type so I can have the connection in the future when we add more properties, so I will not forget to add resource keys.

```
    [ResourceKey("name", Value = "About us page")]
    [ResourceKey("description", Value = "The about us page.")]
    [LocalizedResource(KeyPrefix = "/contenttypes/aboutuspage/", Inherited = false)]
    public class AboutUsPageLocalization : IAboutUsPage
    {
        [ResourceKey("properties/heroimage/caption", Value = "Hero Image")]
        [ResourceKey("properties/heroimage/help", Value =
            "Set hero image, if nothing is set default one will be used.")]
        public Url HeroImage { get; set; }

        [ResourceKey("properties/herotitle/caption", Value = "Hero Title")]
        [ResourceKey("properties/herotitle/help", Value =
            "Set hero title, if nothings is set default one will be used.")]
        public string HeroTitle { get; set; }

        [ResourceKey("properties/contentsections/caption", Value = "Page sections")]
        [ResourceKey("properties/contentsections/help", Value =
            "Set ordered page sections based on different block types")]
        public ContentArea ContentSections { get; set; }
    }
```

**Comment by valdisiljuconoks** [comment]
try with [LocalizedResource] instead. then exception should not be thrown and you are good with single type. then interface will not be needed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bsubasic** [comment]
I've also tried [LocalizedResource] instead of [LocalizedModel] before this, but the web app can't boot up at all - like it's get stuck in lookup and discovery during application startup and I get a page timeout after some time without any error logged or displayed. I get some 'w3wp.exe process errors' displayed in Visual Studio. I have DiagnosticsEnabled property set to true, but no errors found in the logs. When I use [LocalizedResource] in another class like in the example above, everything is OK. So I will stick to it, doesn't have time to investigate because of a short deadline.

**Comment by valdisiljuconoks** [comment]
ah yes.. right. you stepped on the slippery stone now :)

please use `[LocalizedResource]` with either `Inherited = false` or `OnlyIncluded = true`. Otherwise Episerver will turn into Terminator from the future and will hunt you down at night blaming you about generating StackoverflowExceptions on app startup.

This is known issue due to `EPiServer.Core.PageReference.SelfReference` property..


Hint: [https://github.com/valdisiljuconoks/localization-provider-epi/blob/master/tests/DbLocalizationProvider.EPiServer.Sample/Models/Pages/SomeWeirdPage.cs](https://github.com/valdisiljuconoks/localization-provider-epi/blob/master/tests/DbLocalizationProvider.EPiServer.Sample/Models/Pages/SomeWeirdPage.cs)
