### ISSUE TITLE
Multiple resource keys on property throws exception

### ISSUE THREAD

**Issue by tstade** [valdisiljuconoks/LocalizationProvider#139]
While migrating from v3.6 to v5.0 of LocalizationProvider a new exception occurs when having multiple resourcekeys for a property as found in DbLocalizationProvider.Tests.NamedResources.ResourcesWithNamedKeysWithPrefix:

`[ResourceKey("and/1stresource", Value = "Value in attribute")]
[ResourceKey("and/2ndresource")]
public static string SomeResource => "This is property value";`

This test added to NamedResourcesTests reproduces the exception:
`[Fact]
public void ExpressionTest_WithNamedResources_WithPrefix_MultipleResourceKeys_ReturnsException()
{
    var result = ExpressionHelper.GetFullMemberName(() => ResourcesWithNamedKeysWithPrefix.SomeResource);
    Assert.Contains("1stresource", result);
}`

**Comment by valdisiljuconoks** [comment]
hi,

do you have exception details? following test assures that multiple resource keys can exist for property. limitation is for localized model (`[LocalizedModel]`):

[DbLocalizationProvider.Tests.NamedResources.NamedResourcesTests.MultipleAttributesForSingleProperty_WithPrefix](https://github.com/valdisiljuconoks/LocalizationProvider/blob/master/Tests/DbLocalizationProvider.Tests/NamedResources/NamedResourcesTests.cs#L73).

**Comment by tstade** [comment]
The exception is: System.Reflection.AmbiguousMatchException: "Multiple custom attributes of the same type found."

The problem seems to be in ResourceKeyBuilder.BuildResourceKey which presumes a single attribute:
`var resourceKeyAttribute = mi.GetCustomAttribute<ResourceKeyAttribute>();`

**Comment by valdisiljuconoks** [comment]
right. what is your usage? are you trying to render translation for that property somewhere?

**Comment by tstade** [comment]
We're using it in EPiServer for page properties like this:

```
[LocalizedModel(KeyPrefix = "/contenttypes/IContentData/", OnlyIncluded = true)]
public class ExamplePage : BasePageData
{
	[ResourceKey("properties/Property/caption", Value = "Property Headline")]
	[ResourceKey("properties/Property/help", Value = "Explanatory text for property")]
        [Include]
	public virtual string Property { get; set; }
}
```

We use the translated strings for both editors and web pages.

**Comment by tstade** [comment]
Sorry, the earlier exception is only in test. 
The exception thrown on startup while scanning is this:
[InvalidOperationException: Model with data annotation attributes cannot have more than one `[ResourceKey]` attribute.]
 DbLocalizationProvider.Sync.Collectors.<GetDiscoveredResources>d__0.MoveNext() +789

I feel like I'm missing something obvious :)

**Comment by valdisiljuconoks** [comment]
if you are not using ExamplePage as view model (in cases like `@Html.Translate(Model.Property)`) then I would recommend to convert from `[LocalizedModel]` to `[LocalizedResource]`. There is a subtle difference between these 2. And former cannot have multiple `[ResourceKey]` attributes as runtime have no clue which of the key to use when looking for translation. 

think I will need to blog about this difference any time soon.. :)

**Comment by tstade** [comment]
Ah, thank you, I'll see if we can work it out that way!
