### ISSUE TITLE
Missing Translate extention

### ISSUE THREAD

**Issue by coolhotrod** [valdisiljuconoks/LocalizationProvider#140]
In the documentation, it shows using placeholders in your resources by using the translate extension:
`@Html.Translate(() => StartPageResources.GreetingMessage, new { Firstname = "John", Lastname = "Doe" })`
But this extension doesn't seem to be there anymore. Is there another way to do this?

**Comment by valdisiljuconoks** [comment]
nop, it should be still there..

https://github.com/valdisiljuconoks/localization-provider-aspnet/blob/master/src/DbLocalizationProvider.AspNet/HtmlHelperExtensions.cs#L33

**Comment by coolhotrod** [comment]
Ah, okay. That's in the AspNet project. I'm using the AspNetCore project. The docs don't specify that. 
Thanks.

**Comment by valdisiljuconoks** [comment]
yes, I agree. it might look like a bit confusing as there are many packages. but, when it comes to AspNetCore, then you should not use Html helper, but [IStringLocalizer](https://github.com/valdisiljuconoks/localization-provider-core/blob/master/src/DbLocalizationProvider.AspNetCore/IStringLocalizerExtensions.cs#L31) or [IHtmlLocalizer](https://github.com/valdisiljuconoks/localization-provider-core/blob/master/src/DbLocalizationProvider.AspNetCore/IStringLocalizerExtensions.cs#L31).
