### ISSUE TITLE
Exception when using Entity Framework migrations in same solution

### ISSUE THREAD

**Issue by xudonax** [valdisiljuconoks/LocalizationProvider#141]
When we load the LocalizationProvider in Episerver 11.10 while also using EntityFramework 6.2.0 we get weird exceptions when there is a table named `dbo.__MigrationHistory` in the database. This table is, of course, created by EntityFramework itself because we use migrations. The exception we get is `There is already an object named 'LocalizationResources' in the database.`.

Relevant version numbers:
 * LocalizationProvider: 5.0.0
 * LocalizationProvider.Abstractions: 5.0.0
 * LocalizationProvider.AspNet: 5.0.0
 * DbLocalizationProvider.AdminUI.EPiServer: 5.0.0
 * DbLocalizationProvider.EPiServer: 5.0.0
 * EntityFramework: 6.2.0
 * EPiServer.CMS.Core: 11.11.0
 * EPiServer.CMS: 11.10.6

For the complete stacktrace, please see the attached file, [stacktrace.txt](https://github.com/valdisiljuconoks/LocalizationProvider/files/2657427/stacktrace.txt).

**Comment by valdisiljuconoks** [comment]
hm, one option would be to execute migrations manually (to generate content of the __MigrationHistory table with relevant entries for context).
does it happen also when you remove `LocalizationResources` and `LocalizationResourceTranslations` tables from database?

**Comment by xudonax** [comment]
The error persisted with the removal of the `__MigrationHistory` table, but was gone when we removed the `LocalizationResources` table. We haven't removed the `LocalizationResourceTranslations` (yet).

**Comment by valdisiljuconoks** [comment]
it sounds like EF migrations went nuts. removing history table won't help. target tables should be removed..

**Comment by xudonax** [comment]
Seems to be working now, we probably should've tried removing those tables before. Thanks!
