### ISSUE TITLE
Output translations as JSON object

### ISSUE THREAD

**Issue by dnasir** [valdisiljuconoks/LocalizationProvider#147]
I have a multilingual web app that currently uses the `@Html.GetTranslations()` EPiServer helper for rendering the script tag containing the translations for the current language, and I would very much appreciate it if I didn't have to reload the page whenever I need to switch languages. This would also allow me to move my app out of the EPiServer ecosystem.

My suggestion is an API endpoint, that accepts the fully qualified class name of the resource along with the required language key, that outputs the localized text as a JSON object.

**Comment by valdisiljuconoks** [comment]
will be part of 5.5 version
