### ISSUE TITLE
Use EFCore as the Data store

### ISSUE THREAD

**Issue by Garwin4j** [valdisiljuconoks/LocalizationProvider#156]
Hello, I really like the idea of the project (and the work that has been put into it) but I was wondering if using EFCore is in the works. This would allow developers to use whatever data store they are already using and have this killer UI admin to help with localization

**Comment by valdisiljuconoks** [comment]
hi,

request for having other sources than SQL server originated in .NET Core version, but it will be across all platforms once it's done. you can track progress [here](https://github.com/valdisiljuconoks/localization-provider-core/issues/22)

**Comment by Garwin4j** [comment]
Okay cool. That works.
