### ISSUE TITLE
KeyPrefix does not work 

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/LocalizationProvider#159]
Hi,

I tried to use the package maybe not in a way you originally thought of, but it would have been practical for us. Example:

    public class Resources
    {
        public static WebshopResources Webshop { get; }
    }

    [LocalizedResource(KeyPrefix = "Webshop")]
    public class WebshopResources
    {
        public string TestResource1 => "This is default value";

    }
	
Then look up with (although according to code this behavior has nothing to with Episerver):
            var translation = LocalizationService.Current.GetString(() => Resources.Webshop.TestResource1);
	
The upper part creates the resource key Webshop.TestResource1 in database, as I would expect. But the resource accessor lambda expression tries to lookup MyNameSpace.Resources.Webshop.TestResource1, which then it could not find, although Resource class has not LocalizedResource attribute.
(the reason for this naming convention is that there are multiple components like Webshop in our Project, and we wanted a common holder class for all resources - but the customer did not want that to appear in the resource keys)
I tried several thing like LocalizedResource(KeyPrefix = null) but nothing worked.
Is this intended, is there any workaround possible for this? Applying a valid KeyPrefix to Resources class works, I the customer did not want a prefix in the database there.

Using version 5.7.0.

**Comment by nzsb** [comment]
So resource scanner and lookup code return different key in my case.
If you also think the lookup is incorrect, then I found a possible workaround with which I can live with. In my case with Episerver: override the DatabaseLocalizationProvider and remove the FQN prefix for Resources there and then look up.

**Comment by valdisiljuconoks** [comment]
Hi,

Yes indeed, usage is a bit off track.. ;)
Original idea was to use `[ResourceKey]` attribute only to generate specific keys in database (like localization for Episerver Shell resources). But it has very limited role in resource lookup afterwards. It might not be very intuitive, but in general resource key feature I added somewhat not willingly to the lib.

Your workaround might blend.
Sorry for inconveniences.

**Comment by nzsb** [comment]
We do not use [ResourceKey], we tried to use KeyPrefix. But we will remove the Resources class and then it is as intented, so we do not need any fix for this.
