### ISSUE TITLE
Source Code for Admin UI

### ISSUE THREAD

**Issue by infocyde** [valdisiljuconoks/LocalizationProvider#166]
Forgive me if I'm being an idiot and you've already made the source code for the Admin UI accessible somewhere, but I'm missing it.  If it is not available any chance of getting to look at it / tweak it?  Thanks for an awesome project.

**Comment by Sebbe** [comment]
For the epi admin mode, it is here https://github.com/valdisiljuconoks/localization-provider-epi/tree/master/src/DbLocalizationProvider.AdminUI.EPiServer

For the regular asp.net: https://github.com/valdisiljuconoks/localization-provider-aspnet/tree/master/src/DbLocalizationProvider.AdminUI

For dot net core: https://github.com/valdisiljuconoks/localization-provider-core/tree/master/src/DbLocalizationProvider.AdminUI.AspNetCore

Hope this answer some of what you asked :)

**Comment by valdisiljuconoks** [comment]
Thanks Sebastian! I would not recommend to judge epi module source code :) it's terrible and is going to be rewritten if I'm not dead by that timeframe. Asp.Net code is a bit better but not proud either. AdminUI for .NET Core is the most recent, based on Vue.js and has some nice modules (like tree view).
It depends on what you want to modify there. If it's just a styles (look & feel) - that would be doable by "injecting" custom CSS file href. If it's behavior - then I can just wish you good luck in that legacy code ;)
