### ISSUE TITLE
No more class LanguageEntities after upgrade to 6.0.2

### ISSUE THREAD

**Issue by sanderrorije** [valdisiljuconoks/LocalizationProvider#176]
Hi Valdis,
In Januari we had contact about an issue we had. When we opened the Localization tab in EPiServer we saw a page with the text "Page could not be loaded. The link you specified does not work...."
If I remember correctly, you made a hotfix for this but also incorporated the fix in the new 6.x major release. I applied the hotfix and if I remember correctly the problem was fixed.
For some reason the issue returned on our ACC environment. So I'm now upgrading to version 6.0.2.
However our code no longer compiles. We have code to read the translations and write them to Azure Storage. That code uses class LanguageEntities (which implemented DbContext). However this class is no longer available in 6.0.2. I scanned through [this](https://blog.tech-fellow.net/2020/02/21/localization-provider-major-6/) but haven't found a solution yet. Can you help us?
Greetings,
Sander Rorije

**Comment by sanderrorije** [comment]
I have an update. Apparently there were slightly newer 5.x packages available. I've upgraded to these versions. I am now waiting for deployment on ACC. If the issue is fixed, we can postpone the upgrade to version 6 to a later time.

**Comment by valdisiljuconoks** [comment]
Hi,

Yes, LanguageEntities is gone in v6 as EF dependency has been dropped and now I'm talking directly to underlying storage.

This allows now to implement easily custom storage provider (blog post on more details is coming).


Get Outlook for Android<https://aka.ms/ghei36>
________________________________
