### ISSUE TITLE
Missing Blocks in couple International Sites after the Epi Framework Upgrade

### ISSUE THREAD

**Issue by coolgal1980** [valdisiljuconoks/LocalizationProvider#181]
After the code push for Framework Upgrades which involved the Localization Package upgrade:
These were some of the upgrades:
EPiServer.CMS.11.14.2 -> EPiServer.CMS.11.15.0
EPiServer.Forms.4.27.1 -> EPiServer.Forms.4.28.0
EPiServer.Forms.UI.4.27.1 -> EPiServer.Forms.UI.4.28.0
EPiServer.Forms.Core.4.27.1 -> EPiServer.Forms.Core.4.28.0
EPiServer.Find.Cms.13.2.5 -> EPiServer.Find.Cms.13.2.6
EPiServer.CMS.UI.11.23.8 -> EPiServer.CMS.UI.11.24.0
DbLocalizationProvider.AdminUI.EPiServer.5.8.3 -> DbLocalizationProvider.AdminUI.EPiServer.6.0.2
DbLocalizationProvider.EPiServer.5.8.2 -> DbLocalizationProvider.EPiServer.6.0.2
EPiServer.CMS.UI.Core.11.23.8 -> EPiServer.CMS.UI.Core.11.24.0
EPiServer.CMS.AspNet.11.14.2 -> EPiServer.CMS.AspNet.11.15.0
EPiServer.Framework.AspNet.11.14.2 -> EPiServer.Framework.AspNet.11.15.0
EPiServer.Find.Framework.13.2.5 -> EPiServer.Find.Framework.13.2.6
EPiServer.CMS.Core.11.14.2 -> EPiServer.CMS.Core.11.15.0
EPiServer.Framework.11.14.2 -> EPiServer.Framework.11.15.0
LocalizationProvider.AspNet.5.8.2 -> LocalizationProvider.AspNet.6.0.2
LocalizationProvider.5.8.2 -> LocalizationProvider.6.0.2
EPiServer.Find.13.2.5 -> EPiServer.Find.13.2.6
Newtonsoft.Json.10.0.3 -> Newtonsoft.Json.11.0.2
LocalizationProvider.Abstractions.5.8.2 -> LocalizationProvider.Abstractions.6.0.2

We noticed some blocks were missing in a couple of our International sites. I wanted to know if that is related to the localization package upgrade? 
Please let me know if there is anything you know of that might be related to this?

**Comment by valdisiljuconoks** [comment]
Hi,

No, haven't heard of similar issues anywhere. Possible to upgrade only Episerver packages to isolate crime scene?

**Comment by coolgal1980** [comment]
What is this? https://nuget.episerver.com/package/?id=DbLocalizationProvider.MigrationTool
Was I supposed to install this for the upgrade?

**Comment by valdisiljuconoks** [comment]
It's a tool that helps you to migrate resources from xml files to database

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
