### ISSUE TITLE
language fallback problem in v6 (was ok in v5)

### ISSUE THREAD

**Issue by mhwlng** [valdisiljuconoks/LocalizationProvider#184]
We have  these resources in Episerver :
![image](https://user-images.githubusercontent.com/1388886/82814897-549cc800-9e98-11ea-8a88-ab138b88455e.png)

we only entered the main languages [nl,de,fr,en] (with a few exceptions)

![image](https://user-images.githubusercontent.com/1388886/82814925-62eae400-9e98-11ea-8989-798776c155b6.png)

with v5 there was an automatic fallback from e.g. fr-lu to fr or from nl-be to nl or from de-be to de etc.

in v6 I just get the english text, if the language is not the main language

If I use _.FallbackCultures(), then the text language will always be the first in the list

**Comment by valdisiljuconoks** [comment]
Hi,

Can you share your initialization/setup code for provider?

**Comment by mhwlng** [comment]
```
            ConfigurationContext.Setup(_ =>
            {
                _.EnableLegacyMode = () => true;

                _.EnableInvariantCultureFallback = false;
                _.DefaultResourceCulture = new CultureInfo("en");

                var connectionString = ConfigurationManager
                    .ConnectionStrings[EPiServerDataStoreSection.Instance.DataSettings.ConnectionStringName]
                    .ConnectionString;

                _.UseSqlServer(connectionString);
            });   

   UiConfigurationContext.Setup(_ =>
            {
                _.TreeViewExpandedByDefault = true;
                _.ShowInvariantCulture = false;
            });

```

**Comment by valdisiljuconoks** [comment]
Yeah, with v6 fallback languages have changed it's behavior.
Episerver module now in v6 reads fallback languages from `episerver.framework/localization` section in your config file. This makes sure that localization provider follows Episerver set fallback policy for the XML based files provider.
However, if you need to customize this behavior and need different (or mostly you would like to configure fallback due to single language limitation in Episerver) - you can do so in your own init module.

You can use this method to configure your list of fallback languages:
```
ConfigurationContext.Setup(_ =>
{
    _.FallbackCultures.Try(...)
                      .Then(...);
});
```

**Comment by mhwlng** [comment]
I don't think this would work in our situation :

```
  _.FallbackCultures.Try(...)
                      .Then(...);

```
Every language needs a different fallback :

i.e. nl-be needs fallback to nl but fr-be needs fallback to fr


How

**Comment by valdisiljuconoks** [comment]
You sure that this was working in v5? As looking at code where translation is searched for the resource - Episerver configured fallback was implicitly used also.

**Comment by mhwlng** [comment]
Yeah see the v5 picture in the first post above. it's been working fine for a long time. We only set up the 4 main languages nl fr de en

**Comment by valdisiljuconoks** [comment]
Super weird, cause I recreated your case in blank Alloy with custom localization provider and Episerver infrastructure is calling provider only with single fallback language that's being configured in `episerver.framework/localization` element.

Anyhow, gave it a thought and realized that with this feature also pure .NET Core apps might benefit, so added language specific fallbacks if someone will need it. Coming to 6.1

Sample API:

```csharp
ConfigurationContext.Setup(_ =>
{
    // try "sv" -> "no" -> "en"
    _.FallbackCultures
     .Try(new CultureInfo("sv"))
     .Then(new CultureInfo("no"))
     .Then(new CultureInfo("en"));

    // for rare cases - configure language specific fallback
    _.FallbackCultures
     .When(new CultureInfo("fr-BE"))
     .Try(new CultureInfo("fr"))
     .Then(new CultureInfo("en"));
});

```

**Comment by mhwlng** [comment]
ok thanks. that's a good solution for us
