### ISSUE TITLE
Need to restart site after adding new localization strings?

### ISSUE THREAD

**Issue by arthuronoszko** [valdisiljuconoks/LocalizationProvider#195]
Hello!

I am using the LocalizationProvider and it is awesome, thank you!

We are currently having an issue where we need to restart the site in order to get newly added localization keys/strings in the code.

For example:

```
[LocalizedResource]
public class Resources
{
    public static string Heading => "Heading value";
}

```

and using it in a razor view:

`@Html.Translate(() => Resources.Heading)`

It doesn't provide the value `Heading value` until restarting the site. Is it a configuration thing or can it be avoided?

We are using version 6.2.0.0 of the nuget-package.

Thank you!

BR
Arthur

**Comment by valdisiljuconoks** [comment]
Morning!

Which "runtime" are you using? Episerver, .NET Core or "classic" ASP.NET MVC?

**Comment by arthuronoszko** [comment]
> Morning!
> 
> Which "runtime" are you using? Episerver, .NET Core or "classic" ASP.NET MVC?

Sorry, forgot that. I am using Episerver

**Comment by valdisiljuconoks** [comment]
I cannot reproduce this behavior locally unfortunately. Can you tell me more about your process? Do you add property in code and then run rebuild, visit the site and don't see "Heading value"? If so - what do you see instead? Need a bit more details..

**Comment by arthuronoszko** [comment]
So my process is:

Add a new property to Resource class, for example:
`public static string TestString => "This is a value";`

Then add it either to a razor view (with `@Html.Translate(() => ...)`) or via a ViewModel (with ILocalizationProvider.GetString(() => ...)`). Rebuild the solution and refresh the page. Then the localised string is missing.

If I then do a `Debug -> Start Without Debugging`(Or just `Start`, doesn't matter), I can see the localised string in the view.

This is our configuration module:

```    [ModuleDependency(typeof(ServiceContainerInitialization))]
    [ModuleDependency(typeof(PlugInInitialization))]
    public class DbLocalizationProviderConfiguration : IConfigurableModule
    {
        public void ConfigureContainer(ServiceConfigurationContext context)
        {
            string connection = ConfigurationManager.ConnectionStrings["EPiServerDB"].ConnectionString;
            ConfigurationContext.Setup(_ => { _.UseSqlServer(connection); });
        }

        public void Initialize(InitializationEngine context)
        {
            ConfigurationContext.Setup(ctx =>
            {
                string connection = ConfigurationManager.ConnectionStrings["EPiServerDB"].ConnectionString;
                ctx.UseSqlServer(connection);
                ctx.ModelMetadataProviders = new ModelMetadataProvidersConfiguration()
                {
                    ReplaceProviders = false
                };
            });
        }

        public void Uninitialize(InitializationEngine context) { }
    }
```

**Comment by valdisiljuconoks** [comment]
Just wondering - why you are setting up provider twice (in `ConfigureContainer` and `Initialize`)?

**Comment by arthuronoszko** [comment]
I did not write this code, but I agree, it doesn't make sense. It should be enough with just implement the `IInitializableModule` right? I will remove the `IConfigurableModule` interface and try without it.

**Comment by arthuronoszko** [comment]
I have not stripped the configuration to this:

```
    [InitializableModule]
    public class DbLocalizationProviderConfiguration : IInitializableModule
    {
        public void Initialize(InitializationEngine context)
        {
            ConfigurationContext.Setup(ctx =>
            {
                string connection = ConfigurationManager.ConnectionStrings["EPiServerDB"].ConnectionString;
                ctx.UseSqlServer(connection);
                ctx.ModelMetadataProviders = new ModelMetadataProvidersConfiguration()
                {
                    ReplaceProviders = false
                };
            });
        }

        public void Uninitialize(InitializationEngine context) { }
    }
```

Still not working without having to do a `Start without debugging` :/

**Comment by valdisiljuconoks** [comment]
If you enable logging, do you see message that is informing that sync of the resources as been started?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by arthuronoszko** [comment]
So, the values are populated in the databases, and in the Admin interface in Episerver, but when trying to get the value for a key, it doesn't provide any. I will investigate further and see if I can see in the logs where the problem could be.

**Comment by valdisiljuconoks** [comment]
Yeah, weirdo indeed. What if you set PopulateCacheOnStartup to true?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arthuronoszko** [comment]
That did not do anything I'm afraid :( I am trying to download the project as submodules right now, so that I could debug what happens, but am getting `Invalid option '8.0' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6` on a couple of projects. Do you know what I am doing wrong here?
![Screenshot 2020-10-27 at 17 21 58](https://user-images.githubusercontent.com/5484329/97330821-fe81e580-1878-11eb-99f7-81c2b1d135a8.png)

**Comment by valdisiljuconoks** [comment]
VS2019?

**Comment by arthuronoszko** [comment]
Yes, I managed to get it to build, now trying to get it working with our solution :)

**Comment by valdisiljuconoks** [comment]
keep an eye on proper version. here v6.3 is cooking meanwhile :)

**Comment by arthuronoszko** [comment]
Ah okey, I just cloned the Episerver repo, and then installed all submodules. Maybe not that easy? :)

**Comment by valdisiljuconoks** [comment]
I think submodules was bad decision back in days when I split repos :)

**Comment by arthuronoszko** [comment]
They are a bit tricky, yes ;)

**Comment by arthuronoszko** [comment]
I have identified that this line returns `null` for the newly added key, can that help somehow?

This is inside `DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute` on line 32.

`if (!ConfigurationContext.Current.BaseCacheManager.IsKeyKnown(key)) return null;`

After investigating I think it has to do with something in this line in `DbLocalizationProvider.Storage.SqlServer.ResourceSynchronizer.MergeLists`. The property `discoveredResources` contains the newly added key but the `databaseResources` does not, but since the `discoveredModels` is empty, it just returns the resources that are in the database. 

What is strange, (for me :)), is that the after starting the site, the resource is added to the database, I can see it it in the table `dbo.LocalizationResources` and in the admin UI, but I guess it is not added to the `BaseCacheManager` properly?

Hope that this information can tell you something, I can of course investigate more, but do you have an idea of what is happening?

**Comment by valdisiljuconoks** [comment]
Hmm... Interesting. This might lead to a source of the issue. I need to think how to simulate this situation locally to repro this..
Thx for investigation!

**Comment by wojciechGabelBright** [comment]
We are also experiencing this bug in our DXP production environment in episerver. Right now even restarting the app does not help.

**Comment by valdisiljuconoks** [comment]
https://github.com/valdisiljuconoks/LocalizationProvider/pull/200
