### ISSUE TITLE
Locale is case sensitive

### ISSUE THREAD

**Issue by jyparask** [valdisiljuconoks/LocalizationProvider#196]
I recently started messing with the repository and i loved it. In my initial attempt i was creating my classes by adding only one translation in Greek as follows:

    public class Index
    {
        [TranslationForCulture("Χώρα", "el")]
        public static string Country => "Country";
    }

This was for demo purposes in order to familiarize with the library. When all was good and we decided to move on with more translations we started adding the rest of the translations as so:

    public class Index
    {
        [TranslationForCulture("Χώρα", "el")]
        [TranslationForCulture("Pays", "fr-fr")]
        [TranslationForCulture("Pays", "fr-ca")]
        public static string Country => "Country";
    }

Then we started having a strange behavior. First of all, we could not see any translations but instead we were seeing the keys in our web pages, and even the admin ui got terribly wrong. That was in the initial run of the project. When we run the project a second time, it would not load as we were getting sql error messages that we cannot add duplicate keys in LocalizationResourceTranslations table for all 'fr-fr' and 'fr-ca' locales. 

After a lot of fiddling around in order to understand what the cause is i ended up uninstalling the nuget package for the SQL Storage and add the project directly from the repository (add existing project) and start debugging the code. 

The problem seems to be that the library failed to do 'fr-fr' == 'fr-FR' so it was creating an insert statement for 'fr-fr' which subsequently made the SQL insert statement to fail due to key duplication.

My investigation was fruitful and i found that the failing was in ResourceSynchronizer.AddTranslationScript in the following line:

    var existingTranslation = existingResource.Translations.FirstOrDefault(t => t.Language == resource.Culture);

while debugging i found that t.Language was 'fr-FR' and resource.Culture was 'fr-fr' which in c# are not equal. After finding out that i tried updating the TranslationForCulture with the expected case in the culture and all worked fine after that.

If i may suggest a solution on that i would change the code of TranslationForCultureAttribute to properly handle the culture string without putting the developer into the trouble of having to remember the proper casing. For that i suggest the following change on the constructor:

### Existing code:

        public TranslationForCultureAttribute(string translation, string culture)
        {
            Translation = translation;
            Culture = culture;
        }

### Suggested solution:

        public TranslationForCultureAttribute(string translation, string culture)
        {
            Translation = translation;
            Culture = new CultureInfo(culture).ToString();
        }

**Comment by valdisiljuconoks** [comment]
Hi,

Great find! Awesome you hinted that big down. Will pack a new version soon!

Many thanks!
