### ISSUE TITLE
Error: Cannot insert the value NULL into column 'ModificationDate'

### ISSUE THREAD

**Issue by valdisiljuconoks** [valdisiljuconoks/LocalizationProvider#198]
```
Cannot insert the value NULL into column 'ModificationDate', table 'dbo.LocalizationResourceTranslations'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
```

This happens when you have resource translations with no associated resource (this is basically stale data, but lib should survive).

**Comment by Hyzac** [comment]
Ran in to this issue today when upgrading from 5.8. Is ther a fix/workaround?

**Comment by valdisiljuconoks** [comment]
I think that might be culprit here. Haven't worked yet on reviewing and fixing this.
