### ISSUE TITLE
Missing method ResourceSyncronizer.RegisterManually in version 6.x

### ISSUE THREAD

**Issue by andreas-valtech** [valdisiljuconoks/LocalizationProvider#199]
We are currently using DbLocalizationProvider version 5.8 with EPiServer and are using the method RegisterManually on ResourceSynchronizer (https://github.com/valdisiljuconoks/LocalizationProvider/issues/8) to register some resources that come from an outside source.

When upgrading to version 6.x this method seems to be missing. We can see that storage has ben split up into multiple packages and we're using SQL Server so we installed LocalizationProvider.Storage.SqlServer package. It seems this method was just lost in the restructuring?

We have looked at the ResourceRepository but it does not contain any method to insert OR update a resource so we would have to write code to sync resources manually using AddResource/AddTranlation.

Any plans to bring this method back?

**Comment by valdisiljuconoks** [comment]
hmm, yes. indeed.

wtf?

**Comment by valdisiljuconoks** [comment]
here just for ref (copy from decompiled 5.x version):

```
public void RegisterManually(IEnumerable<ManualResource> resources)
    {
        string defaultCulture = (string) IQueryExtensions.Execute<string>((IQuery<M0>) new DetermineDefaultCulture.Query());
        foreach (ManualResource resource in resources)
          this.RegisterIfNotExist(db, resource.Key, resource.Translation, defaultCulture, "manual");
        db.SaveChanges();
    }
```

**Comment by valdisiljuconoks** [comment]
You can find more info at  https://github.com/valdisiljuconoks/LocalizationProvider/blob/master/docs/sync-net.md#register-manually-resources

**Comment by andreas-valtech** [comment]
> You can find more info at https://github.com/valdisiljuconoks/LocalizationProvider/blob/master/docs/sync-net.md#register-manually-resources

Awesome, thanks! 👍
