### ISSUE TITLE
Missing text after update from v5.0.1 to v5.7.6

### ISSUE THREAD

**Issue by nitinanand27** [valdisiljuconoks/LocalizationProvider#208]
After recent upgrade of DBLocalizationProvider from v5.0.1 to v5.7.6 in project i see that translations from Database are missing. 

`public static class Global {

[LocalizedResource(KeyPrefix = "/common/globalstrings/")]
		public static class LocalizationStringKeys
		{
			[ResourceKey("fact", "Fact")]
			public const string Fact = "/common/globalstrings/fact";
    }
}`

Trying to render value in view as 
`@Html.Translate(Global.LocalizationStringKeys.Fact)`

Result:-

![image](https://user-images.githubusercontent.com/15047308/109144386-67169b80-7761-11eb-8538-bb110d698b03.png)

Is there a way to retreive them without needing to readd them in cms?

**Comment by valdisiljuconoks** [comment]
Hej,

Is this simple ASP.NET MVC project?

**Comment by nitinanand27** [comment]
Hi Valdis
Its an Episerver project with cms version 11.11.0

**Comment by valdisiljuconoks** [comment]
Ok,

Check config files. I've seen cases when (especially combined with Epi upgrades at the same time) localization element has changed order of the providers there. Resulting in either XML provider or DbLocalizationProvider missing the chance to return the resource. As that list acts as "first wins".

**Comment by nitinanand27** [comment]
It seems ok here. Anything else i should be checking?

`    <localization fallbackBehavior="Echo, MissingMessage, FallbackCulture" fallbackCulture="en">
      <providers>
        <add name="db" type="DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider, DbLocalizationProvider.EPiServer" />
      </providers>
    </localization>`

**Comment by valdisiljuconoks** [comment]
Looks OK.

Fallback behavior is also OK for your site (having Echo as first behavior)? Does resource exist in storage under this key?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nitinanand27** [comment]
No idea about echo. Thought of sharing setup code

`    [InitializableModule]
    public class DbLocalizationProviderInitialization : IInitializableModule
    {
        public void Initialize(InitializationEngine context)
        {
            ConfigurationContext.Setup(
                ctx =>
                {
                    ctx.DefaultResourceCulture = new CultureInfo("en");
					ctx.DiscoverAndRegisterResources = true;
					ctx.PopulateCacheOnStartup = false;
					ctx.ModelMetadataProviders.EnableLegacyMode = () => true; //Support forward slash/Xpath-style
                });
        }
        public void Uninitialize(InitializationEngine context) { }
    }`

**Comment by valdisiljuconoks** [comment]
Try enabling cache population during startup.
Version (5.7.6) is pretty old so that’s why I am bit guessing here…

**Comment by nitinanand27** [comment]
hmm understand, upgrade to v6 needs us to even upgrade episerver cms. However,i tried with ctx.PopulateCacheOnStartup = true; but no luck.

**Comment by valdisiljuconoks** [comment]
this should be fixed in upcoming v7
