### ISSUE TITLE
Migration/refactoring using RenamedResource causes duplicate key exception if original key reappears after first migration

### ISSUE THREAD

**Issue by HaavardGrendal** [valdisiljuconoks/LocalizationProvider#212]
Hi,

We have tried to use RenameResource attribute when refactoring our resources and have stumbled upon an issue particularly in our development environment with several active branches.
If I add a RenameResource attribute in one branch, it will migrate these resources to the new resource keys and the old resource keys will no longer exist.
If I then switch over to the other branch where this migration has not been done, the old resource keys will reappear in the database.
And finally when I switch back to the branch with the migration, the migration will throw exceptions saying "Cannot insert duplicate key row in object 'dbo.LocalizationResources' with unique index 'IX_ResourceKey'. The duplicate key value is ..."
This could also happen in other environments if an old resource key for some reason is readded.

I got this working by adding following T-SQL to ResourceSynchronizer.RegisterDiscoveredResources (line 161) in DbLocalizationProvider.Storage.SqlServer:
AND NOT EXISTS(SELECT 1 FROM LocalizationResources WITH(NOLOCK) WHERE ResourceKey = '{refactoredResource.Key}')

More code to clarify:
`var refactoredResources = group.Where(r => !string.IsNullOrEmpty(r.OldResourceKey));
                                 foreach(var refactoredResource in refactoredResources)
                                 {
                                     sb.Append($@"
        IF EXISTS(SELECT 1 FROM LocalizationResources WITH(NOLOCK) WHERE ResourceKey = '{refactoredResource.OldResourceKey}')
            AND NOT EXISTS(SELECT 1 FROM LocalizationResources WITH(NOLOCK) WHERE ResourceKey = '{refactoredResource.Key}')
        BEGIN
            UPDATE dbo.LocalizationResources SET ResourceKey = '{refactoredResource.Key}', FromCode = 1 WHERE ResourceKey = '{refactoredResource.OldResourceKey}'
        END
        ");
                                 }`

For development environment it would be nice if the old resource keys wouldn't be lost. For instance if we could configure somehow that migration should insert new key using the values of the old resource and not update the existing key. That would be a great feature for us. :slightly_smiling_face: 

Best regards,
Håvard Grendal

**Comment by valdisiljuconoks** [comment]
Hei,

This sounds like a low hanging fruit and could be added to the upcoming v7.0 :)

Thanks for the feedback!

**Comment by valdisiljuconoks** [comment]
This might work for you?

```csharp
[LocalizedModel]
[RenamedResource("OldModelClassAndProperty")]
public class RenamedModelClassAndProperty
{
    [RenamedResource("OldProperty", CreateNewResource = true)]
    public string NewProperty { get; set; }
}
```

**Comment by HaavardGrendal** [comment]
Do you plan to use CreateNewResource to configure that migration should insert new key using the values of the old resource and not update the existing key? If this is the case it will work for us.

**Comment by valdisiljuconoks** [comment]
Yup, exactly. So it could be set for individual resources – strategy how to refactor and what to do with old resource.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by HaavardGrendal** [comment]
Perfect. That would be great. 😊

**Comment by valdisiljuconoks** [comment]
Actually thinking this through again, came to conclusion that this should be global setting. It's kinda rare that you would like to configure creation of new resource individually for single resource. It's more like that you tell provider - "ok, ignore existing resources. it's fine!"

so will add this configuration to global scope.

**Comment by valdisiljuconoks** [comment]
During the setup:

```
Configuration.Context.FlexibleRefactoringMode = true;
```
