### ISSUE TITLE
Adding new language translations using AdminUI

### ISSUE THREAD

**Issue by sixeyes** [valdisiljuconoks/LocalizationProvider#213]
I'm trying to understand how to add translations other than "en". I'm navigated to the AdminUI page and I get the following:

```
Localization Resources

Resource Key | English | From Code | Delete
_____________+_________+___________+_______
```

Is there more than one page?

I've searched around the site but all the guides seem to show how to set up the code to enable localization, not how to actually get translated translated text into the database.

I thought AdminUI was the tool but it only seems to be offering me English, so perhaps I've misunderstood or my installation is not configured correctly.

In case it matters I'm using ASP.NET MVC and .NET v4.7.2 for the AdminUI.

**Comment by valdisiljuconoks** [comment]
Yeah, library follows supported language list (from setup code). Library itself has no idea what languages are supported.

**Comment by sixeyes** [comment]
My setup code has the following:

```
			var supportedCultures = new[]
			{
				new CultureInfo("fr"),
				new CultureInfo("fr-BE"),
				new CultureInfo("fr-CA"),
				new CultureInfo("fr-CH"),
				new CultureInfo("fr-FR"),
				new CultureInfo("de"),
				new CultureInfo("de-AT"),
				new CultureInfo("de-CH"),
				new CultureInfo("de-DE"),
				new CultureInfo("es"),
				new CultureInfo("it"),
				new CultureInfo("it-CH"),
				new CultureInfo("it-IT"),
			};

			appBuilder.UseDbLocalizationProvider(o =>
			{
				o.DefaultResourceCulture = new CultureInfo("en");
				o.FallbackCultures.Try(supportedCultures);
				o.UseSqlServer(panelConnectionString);
			});
```

But still I only got English.

Any ideas?

**Comment by valdisiljuconoks** [comment]
Oh, you can override available language handler and return all supported languages there. Sample setup code:

```
appBuilder.UseDbLocalizationProvider(o =>
{
    o.TypeFactory.ForQuery<AvailableLanguages.Query>().SetHandler<MyAvailableLanguagesHandler>();
});
```
