### ISSUE TITLE
Language translation not returned

### ISSUE THREAD

**Issue by sixeyes** [valdisiljuconoks/LocalizationProvider#214]
I have created localizations for text on my Razor page and I'm using @Html.Translate() to get the translated text.

I have two text messages and I have created the following in my database:

```
ResourceId | Language |  Value
-----------+----------+----------------------------------
         6 |          | Enter our Community
         6 |   en     | Enter our Community
         6 |   fr     | Entrez dans notre communauté
         6 |   fr-BE  | Entrez dans notre communauté (BE)
         7 |          | Remember My Login
         7 |   en     | Remember My Login
         7 |   fr     | Se souvenir de ma connexion
         7 |   fr-BE  | Se souvenir de ma connexion (BE)
         7 |   fr-CA  | Se souvenir de ma connexion (CA)
         7 |   fr-CH  | Se souvenir de ma connexion (CH)
         7 |   fr-FR  | Se souvenir de ma connexion (FR)
```
If I set my browser's language to "fr" or "fr-BE" both text messages are translated. If I send my browser's language to "fr-CA", "fr-CH" or "fr-FR" the message for resourceId 6 is in English but the message for resourceId 7 is translated.

The Microsoft language translation guides state that if a country specific culture is no available it will fall back to the language specific culture before falling back to English.

My setup code is configured as:

```
var supportedCultures = new[]
{
    new CultureInfo("fr"),
    new CultureInfo("fr-BE"),
    new CultureInfo("fr-CA"),
    new CultureInfo("fr-CH"),
    new CultureInfo("fr-FR"),
    new CultureInfo("de"),
    new CultureInfo("de-AT"),
    new CultureInfo("de-CH"),
    new CultureInfo("de-DE"),
};

services.AddDbLocalizationProvider(o => o.UseSqlServer(panelConnectionString));
services.Configure<RequestLocalizationOptions>(o =>
{
    o.DefaultRequestCulture = new RequestCulture("en");
    o.SupportedCultures = supportedCultures;
    o.SupportedUICultures = supportedCultures;
});
services.AddDbLocalizationProvider(setup =>
{
    setup.EnableInvariantCultureFallback = true;
    setup.FallbackCultures.Try(supportedCultures);
    setup.ScanAllAssemblies = true;
    setup.UseSqlServer(panelConnectionString);
});
```

**Comment by valdisiljuconoks** [comment]
If I recall correctly translation lookup is strictly following `FallbackLanguages` list. Try shuffling it a bit around to see if that makes any difference. If not - then sounds like a obvious bug.

**Comment by sixeyes** [comment]
Thanks for that. I re-ordered the list and having "fr" after all the French variants and it worked as expected :)
