### ISSUE TITLE
No possible to save selected languages when the list is larger than the screen

### ISSUE THREAD

**Issue by oyvindwh** [valdisiljuconoks/LocalizationProvider#232]
Missing a scrollbar when the list of languages are long. Workaround is to zoom out in the browser to make the button visible.

![image](https://user-images.githubusercontent.com/106393/139043605-6d36a827-19fa-449b-a2b5-c54f449fb4d0.png)

**Comment by valdisiljuconoks** [comment]
Found in pre-0006
