### ISSUE TITLE
Null exception when app starts

### ISSUE THREAD

**Issue by daiduongbian44** [valdisiljuconoks/LocalizationProvider#242]
Hi @valdisiljuconoks ,
We're glad to know this lib and this also helps us many thing on our current project.
When working with this lib, we detected the error can be minor changes
on ResourceSynchronizer.
In line: `var invariant = discoveredResource.Translations.FirstOrDefault(t2 => t.Language == string.Empty);`
We'd like to suggest change to:
`var invariant = discoveredResource.Translations.FirstOrDefault(t2 => t2.Culture == string.Empty);`
This change can avoid the throwing null exception when app starts.
![image](https://user-images.githubusercontent.com/6070938/154473499-4c6a416e-2edf-4de0-bf5f-ad865aa843b4.png)
![image](https://user-images.githubusercontent.com/6070938/154473699-cc6a6bf0-1f0f-4072-902a-05aec84bd84f.png)
Thanks for your and the team's contribution!

**Comment by valdisiljuconoks** [comment]
Hey,

After reviewing the code - I found that this issue is already fixed in v7

**Comment by daiduongbian44** [comment]
Yeah,
We're also using DbLocalizationProvider.AdminUI.EPiServer.Xliff, and the latest version is 6.5.0. So we can't make the LocalizationProvider to higher version 👍

**Comment by valdisiljuconoks** [comment]
Oh crap. Ok, will try to backport to 6.5.1

**Comment by valdisiljuconoks** [comment]
Look for 6.5.2 version on the feed. Should be fixed there!
Thx for reporting!

Stay safe!

**Comment by daiduongbian44** [comment]
We really appreciate this, thank @valdisiljuconoks 
Very quick actions, thanks the team!
