### ISSUE TITLE
Properties with UseResourceAttribute returns null

### ISSUE THREAD

**Issue by stefanolsen** [valdisiljuconoks/LocalizationProvider#265]
I have a good number of translation classes in a project. Some of them has UseResource attributes, like the following:
```
[LocalizedResource]
[TsInterface]
public class AResourceClass
{
    public string LabelOne { get; set; } = "An English text";

    [UseResource(typeof(GlobalResources), nameof(GlobalResources.ASharedLabel))]
    public string LabelTwo { get; set; }
}
```

If I call `_localizationProvider.Translate<AResourceClass>()`, then LabelOne will have a value, while LabelTwo will be `null`. 

But explicitly requesting only the LabelTwo property, like the following, returns the expected string:
`_localizationProvider.GetString(_resourceKeyBuilder.BuildResourceKey(typeof(AResourceClass), nameof(AResourceClass.LabelTwo)))`

**Package version:**
- LocalizationProvider: 7.5.1
- LocalizationProvider.Storage.SqlServer: 7.5.1

**Comment by valdisiljuconoks** [comment]
Hi Stefan,

Sounds like a bug. Will take a look at next round for release (January timeline).
