### ISSUE TITLE
Resources not getting caches after upgrade to 8.0.2

### ISSUE THREAD

**Issue by toregjerdrum** [valdisiljuconoks/LocalizationProvider#285]
Hi,

After upgrading our Optimizely site to .NET 8 and upgrading DbLocalizationProvider to 8.0.2, it does not look like the resources are getting cached anymore. When running on DbLocalizationProvider 7.5.1, I see that the ConfigurationContext.CacheManger.OnInsert is being trigged, but when running on DbLocalizationProvider 8.0.2, the event is never trigged. I also created my own IResourceRepository and the GetAll method only gets called on startup when running on 7.5.1. When running on 8.0.2, the GetAll method gets called all the time. 

I could not see anything on your [blog](https://tech-fellow.eu/2024/02/28/localization-provider-v8-released/) mentioning that we needed to do any registration on caching when upgrading to v8. Have you seen this when testing? Is this a bug or am I missing any registrations? I have not done anything other then upgrading to .NET 8 and upgrading all nuget packages to latest version. I get the same error on all 3 sites I have tested it on.

**Comment by valdisiljuconoks** [comment]
hi, seems like cache event subscriptions are lost when app starts..

**Comment by toregjerdrum** [comment]
Hi Valdis,

Thanks for the quick response and a fix to the problem. The cache events are now trigged on startup, but my application is not able to start any more. An exception is thrown in the UseDbLocalizationProvider method when doing sync, see attached photo.
<img width="617" alt="image" src="https://github.com/valdisiljuconoks/LocalizationProvider/assets/1195937/e75091ab-9bfb-4180-8885-a6ff0bd5d13b">

**Comment by valdisiljuconoks** [comment]
Opti packages were not pushed out yet, as Opti login was not working yesterday ;)

**Comment by valdisiljuconoks** [comment]
Opti packages submitted to the feed

**Comment by toregjerdrum** [comment]
@valdisiljuconoks: Thanks! Works now!
