### ISSUE TITLE
Request: Adding automatic handling for Categories

### ISSUE THREAD

**Issue by camistein** [valdisiljuconoks/LocalizationProvider#50]
Right now i manually add it foreach category:
var key = $"/categories/category[@name=\"{cat.Name}\"]/description";
          
var synchronizer = new ResourceSynchronizer();
synchronizer.RegisterManually(new[] { new ManualResource(key, cat.Name) });

if  
DbLocalizationProvider.LocalizationProvider.Current.GetString(key) returns empty.

**Comment by valdisiljuconoks** [comment]
Hi,

Yes, categories somehow was not in the scope so far. Thanks for request. I'll look into that. Btw, how do you define categories? In code?

**Comment by valdisiljuconoks** [comment]
Hi,

This works for me:

```
[LocalizedResource(KeyPrefix = "/categories/")]
public class Categories
{
    [ResourceKey("category[@name=\"SampleCategory\"]/description")]
    public static string SampleCategory => "This is sample cat. from code";
}
```

Resulting resource key for the category will be (composite from `LocalizedResource.KeyPrefix` and `ResourceKey` attributes):

```
/categories/category[@name="SampleCategory"]/description
```


You can also write above code in following way:

```
[LocalizedResource]
public class Categories
{
    [ResourceKey("/categories/category[@name=\"SampleCategory\"]/description")]
    public static string SampleCategory => "This is sample cat. from code";
}
```

Or also:

```
[ResourceKey("category[@name=\"" + nameof(SampleCategory) + "\"]/description")]
public static string SampleCategory => "This is sample cat. from code";
```

Pick whatever style you like.

**Comment by valdisiljuconoks** [comment]
If code like this does not register resources with proper keys and categories are localized in Cms UI -> please reopen issue with more specific details.
