### ISSUE TITLE
Compatibility with Episerver nuget packages above v.10.0.0

### ISSUE THREAD

**Issue by christofferkindesjo** [valdisiljuconoks/LocalizationProvider#51]
The current version of LocalizationProvider doesn't allow Episerver.Cms.Core or Episerver.Cms.UI.Core above 10.0.0. This blocks a lot of other packages from updating. It would be very helpful if you released a version with support for the latest versions of those packages.
Thank you!

**Comment by valdisiljuconoks** [comment]
Plan is to release compatible packages within next week. Stay tuned!

**Comment by christofferkindesjo** [comment]
That is great news! Thank you for the quick answer.

**Comment by valdisiljuconoks** [comment]
Look for v3.0 on nuget feeds. cheers!
