### ISSUE TITLE
MigrationTool doesn't support unicode characters

### ISSUE THREAD

**Issue by tholee** [valdisiljuconoks/LocalizationProvider#70]
INSERT dbo.LocalizationResourceTranslations (ResourceId, Language, Value) VALUES (@id, 'no', N'GÃ¥ direkte til hovedmenyen');

should have been "Gå direkte til hovedmenyen"

**Comment by valdisiljuconoks** [comment]
What a dumb bug :) Look for 2.3.1 version for EPiServer v9, and 3.3.1 for v10.

Thanks for finding!
