### ISSUE TITLE
Exception thrown in legacy mode

### ISSUE THREAD

**Issue by tholee** [valdisiljuconoks/LocalizationProvider#72]
When a legacy localized model uses other data annotations without Display an exception is thrown
Eg.

    [LocalizedModel(OnlyIncluded =true)]
    public class Model
    {
        [Required] //Throws exeception due to missing translation
        public string ComputerGenerated { get; set; }

        [Display(Name = "/legacy/username")]
        [Include]
        public string UserName { get; set; }

    }

**Comment by valdisiljuconoks** [comment]
Thx, interesting use case and not discovered bug. Merging and pushing packages out.

**Comment by valdisiljuconoks** [comment]
Fixed in 2.6.1
