### ISSUE TITLE
Translating properties from base classes

### ISSUE THREAD

**Issue by christofferkindesjo** [valdisiljuconoks/LocalizationProvider#75]
For page types the translation of base class properties can be achieved by adding the resource key "/contenttypes/IContentData/properties/[property]/caption". 
I want this for block types as well but I can't seem to find a way. Can this be achieved in the current build or will it be implemented in the future?

**Comment by valdisiljuconoks** [comment]
Hi,

What is the required XPath key for the block type base properties?

**Comment by christofferkindesjo** [comment]
Hi,
Say that we have a property called "Headline" on both a page base class and a block base class but we want to have different default values. For instance:
/contenttypes/[PageBaseClass]/properties/HeadLine/caption  = "Page headline"
/contenttypes/[BlockBaseClass]/properties/HeadLine/caption = "Block headline"

Using IContentData in the path would let us set one default value but not differentiate between the two.
Is it possible to use the base class in the XPath key?

**Comment by valdisiljuconoks** [comment]
How do you add resource with XPath as key today?

**Comment by christofferkindesjo** [comment]
We add the keys manually in the epi admin interface for DbLocalizationProvider.

**Comment by valdisiljuconoks** [comment]
What about this?

```
[LocalizedResource]
public class EPiServerContentTypeTranslations
{
    [ResourceKey("/contenttypes/OurBasePage/properties/HeadLine/caption", Value = "Page headline")]
    public static string PageHeadline { get; set; }

    [ResourceKey("/contenttypes/OurBaseBlock/properties/HeadLine/caption", Value = "Block headline")]
    public static string BlockHeadline { get; set; }
}
```

More info: https://github.com/valdisiljuconoks/LocalizationProvider/blob/master/docs/resource-types.md#resource-keys

**Comment by valdisiljuconoks** [comment]
@christofferkindesjo can we close this?

**Comment by christofferkindesjo** [comment]
Hi,

Yes, please close this ticket.
Thank you!

BR,
Christoffer
