### ISSUE TITLE
Doesn't support Htmlhelpers in legacymode

### ISSUE THREAD

**Issue by tholee** [valdisiljuconoks/LocalizationProvider#76]
When running in legacy-mode the model
![image](https://user-images.githubusercontent.com/1217446/26880073-964a3f04-4b93-11e7-9295-643996ad409d.png)

and the view
![image](https://user-images.githubusercontent.com/1217446/26880109-a9f0f840-4b93-11e7-9e0f-1c28d53fbc23.png)

generates
![image](https://user-images.githubusercontent.com/1217446/26880060-8d4cd524-4b93-11e7-943b-3e7196d68ba5.png)
 But it should have been 
![image](https://user-images.githubusercontent.com/1217446/26880155-d102a8c0-4b93-11e7-885e-0058e177b2d8.png)

**Comment by valdisiljuconoks** [comment]
Awesome! Seems like legacy mode was not properly tested :)

Thx. Will merge and release as soon as land on solid ground..

**Comment by valdisiljuconoks** [comment]
Btw, @tholee - are you working with EPiServer v9?

**Comment by valdisiljuconoks** [comment]
Look for v2.3.2. I haven't locked down upper version limit tho. 2.6.x is used in EPiServer v10 context. Haven't actually tested v2.6 in Epi v9 site.
