### ISSUE TITLE
Add support for LoadBalance scenarios

### ISSUE THREAD

**Issue by wrojas** [valdisiljuconoks/LocalizationProvider#9]
Hello Valdis,

This is great stuff, I have previously used the Localization Provider from Jeroen and it really improved the Editor Experience.
Now that you have created a new alternative, I wanted to give you my two cents of one of the scenarios that sometimes adds complexity:

 - Handling of Load Balanced scenarios, to invalidate cache in web-fronts upon update of translations.

Jeroen solved the issue by adding event handlers to the remote events on EPiServer (since the translations are pages)

In your implementation, it seems like you are using CacheManager, correct?
If so, I can see two options to enable NLB scenarios:
- Use Redis as a centralized out-of-process cache (http://social.technet.microsoft.com/wiki/contents/articles/26711.asp-net-webapi-use-redis-as-cachemanager.aspx)
- Increase complexity to manage cache expiration.

Please let me know if my comments makes sense, and happy to help/further converse :)

Keep up the library creation! It is quite refreshing.

Regards,
. Wacdany

**Comment by valdisiljuconoks** [comment]
Hi,

Thanks for your time. When it comes to caching I read all the comments you made and Jeroen in his site. And here are my 2 cents:
1) I cannot decide to use Redis for caching on-behalf of hosting project as it's usually related to costs and resources in the cloud. If hosting project wants to use Redis for caching - it has to be done explicitly - it's not library's neither responsibility nor power to decide.
2) If code is using CacheManager - it's designed to handle web farms and NLB scenarios and internally it uses remote cache invalidations as well (implemented as events via Azure Service Bus if we take a look at Azure deployment case).

If NLB is used on-premises, then I guess as far as CacheManager / Remote Events infrastructure is setup correctly and all nodes can communicate with each other about what happened in one of the nodes - you  should be fine.

These all are just my humble speculations as I haven't heavily tested in NLB cases - but I do rely on EPiServer code- that these cases should be handled there already!


Please comments if I'm wrong here..

Thanks!

**Comment by wrojas** [comment]
Hi Valdis,

Now that is a fast reply back!
My feedback on your comments:

1) I agree, using Redis for caching shouldn't be a responsibility of the library but rather a design decision for the project overall. 
2) An overlook on my side that the EPiServer Cache manager already handles webfarm scenarios (http://world.episerver.com/documentation/class-library/?documentId=cms/7/393fb0eb-1b68-6b94-1a01-66a84365e1d3) 

That being said, also humble speculations over here! Can't wait to get a chance to use the library in a new project and let you know practical feedback :)

Thank you for your time putting this together (as well as feature switch)!
. Wac

**Comment by valdisiljuconoks** [comment]
My joy to help fellows to resolve same issues that I facing.. :)
