### ISSUE TITLE
When upgrading the package from NuGet, internal resource-keys are missing

### ISSUE THREAD

**Issue by MunchyYDL** [valdisiljuconoks/LocalizationProvider#93]
After an upgrade to the latest packages on NuGet, the newly added/changed internal resource-keys wasn't added to the database, which caused the UI to display the keys.

i.e. these keys:
* DbLocalizationProvider.AdminUI.Resources.TableView
* DbLocalizationProvider.AdminUI.Resources.TreeView
* DbLocalizationProvider.AdminUI.Resources.ExpandAll
* DbLocalizationProvider.AdminUI.Resources.CollapseAll
* DbLocalizationProvider.AdminUI.Resources.ShowHidden

Maybe you can register them during the installation of the package?

**Comment by valdisiljuconoks** [comment]
Do you have any assembly filter for scanning setup?

```
ConfigurationContext.Setup(ctx => ctx.AssemblyScanningFilter = () => ...)
```

**Comment by valdisiljuconoks** [comment]
This was fixed in #91. So should be in the package already.

**Comment by valdisiljuconoks** [comment]
@MunchyYDL can we close this?

**Comment by valdisiljuconoks** [comment]
@MunchyYDL if you have precise repo steps - please reopen.
