### ISSUE TITLE
xliff import or export is wrong

### ISSUE THREAD

**Issue by Sebbe** [valdisiljuconoks/LocalizationProvider#98]
Hi, I did an export of my translations using the xliff, and changed one text field. But when I selected import then the importer wanted to delete and add many things.

Looks like the issue is originates from #97 because I see that in the admin view that the resource key is like this:
Norrona.Commerce.Framework.Models.Address.City-Required
but when imported it is with a + in front Norrona.Commerce.Framework.Models.Address.City+Required

So the importer want to remove those with - and add new ones with +

See attached images

![image](https://user-images.githubusercontent.com/814625/29602309-e6ca6016-87df-11e7-96fe-2759e46fbf59.png)
![image](https://user-images.githubusercontent.com/814625/29602328-fcb6450c-87df-11e7-8e24-f132483ea43d.png)

**Comment by valdisiljuconoks** [comment]
xliff will kill me :)

**Comment by valdisiljuconoks** [comment]
should be fixed in 2.8.2. thx for discovering this bug @Sebbe
